/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMintableToken,
  IMintableTokenInterface,
} from "../IMintableToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "dest",
        type: "address",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "mint",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IMintableToken__factory {
  static readonly abi = _abi;
  static createInterface(): IMintableTokenInterface {
    return new Interface(_abi) as IMintableTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMintableToken {
    return new Contract(address, _abi, runner) as unknown as IMintableToken;
  }
}
