/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IDividendsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getNumTokenHolders"
      | "getTokenHolder"
      | "getWithdrawableDividend"
      | "recordDividend"
      | "withdrawDividend"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getNumTokenHolders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenHolder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawableDividend",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordDividend",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawDividend",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getNumTokenHolders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawableDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawDividend",
    data: BytesLike
  ): Result;
}

export interface IDividends extends BaseContract {
  connect(runner?: ContractRunner | null): IDividends;
  waitForDeployment(): Promise<this>;

  interface: IDividendsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getNumTokenHolders: TypedContractMethod<[], [bigint], "view">;

  getTokenHolder: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getWithdrawableDividend: TypedContractMethod<
    [payee: AddressLike],
    [bigint],
    "view"
  >;

  recordDividend: TypedContractMethod<[], [void], "payable">;

  withdrawDividend: TypedContractMethod<
    [dest: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getNumTokenHolders"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTokenHolder"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getWithdrawableDividend"
  ): TypedContractMethod<[payee: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordDividend"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "withdrawDividend"
  ): TypedContractMethod<[dest: AddressLike], [void], "nonpayable">;

  filters: {};
}
